# permissions for end users to view fermats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fermat-viewer-role
rules:
- apiGroups:
  - math.potsbo.k8s.wantedly.com
  resources:
  - fermats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - math.potsbo.k8s.wantedly.com
  resources:
  - fermats/status
  verbs:
  - get
