# permissions for end users to view numbers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: number-viewer-role
rules:
- apiGroups:
  - math.potsbo.k8s.wantedly.com
  resources:
  - numbers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - math.potsbo.k8s.wantedly.com
  resources:
  - numbers/status
  verbs:
  - get
