
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - math.potsbo.k8s.wantedly.com
  resources:
  - fermats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - math.potsbo.k8s.wantedly.com
  resources:
  - fermats/finalizers
  verbs:
  - update
- apiGroups:
  - math.potsbo.k8s.wantedly.com
  resources:
  - fermats/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - math.potsbo.k8s.wantedly.com
  resources:
  - numbers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - math.potsbo.k8s.wantedly.com
  resources:
  - numbers/finalizers
  verbs:
  - update
- apiGroups:
  - math.potsbo.k8s.wantedly.com
  resources:
  - numbers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - math.potsbo.k8s.wantedly.com
  resources:
  - tuples
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - math.potsbo.k8s.wantedly.com
  resources:
  - tuples/finalizers
  verbs:
  - update
- apiGroups:
  - math.potsbo.k8s.wantedly.com
  resources:
  - tuples/status
  verbs:
  - get
  - patch
  - update
