# permissions for end users to view tuples.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tuple-viewer-role
rules:
- apiGroups:
  - math.potsbo.k8s.wantedly.com
  resources:
  - tuples
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - math.potsbo.k8s.wantedly.com
  resources:
  - tuples/status
  verbs:
  - get
