# permissions for end users to edit tuples.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tuple-editor-role
rules:
- apiGroups:
  - math.potsbo.k8s.wantedly.com
  resources:
  - tuples
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - math.potsbo.k8s.wantedly.com
  resources:
  - tuples/status
  verbs:
  - get
